### ISSUE TITLE
Create Tag for Imgur Implementation

### ISSUE THREAD

**Issue by raskasa** [JakeWharton/u2020#143]
@mattprecious I asked this at Droidcon, but asking here just in case.  Is it possible to create a tag of the codebase just before the GitHub implementation (when the Imgur API was being used)?

**Comment by JakeWharton** [comment]
The first commit was here: https://github.com/JakeWharton/u2020/commit/a565a1afd1605b771b8055a1f48d80e59fba09ff

**Comment by raskasa** [comment]
Thanks.
