### ISSUE TITLE
unable to load class 'org.codehaus.groovy.runtime.typehandling.shorttypehandling'

### ISSUE THREAD

**Issue by vandzi** [JakeWharton/u2020#167]
Not sure whether this is project issue or android studio issue but it happens only with this project so I am reporting it. When project is opened in android studio it displays error: 

Failed to sync Gradle project 'u2020'
Error:Unable to load class 'org.codehaus.groovy.runtime.typehandling.ShortTypeHandling'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

It builds fine via command line.
Android studio 1.3 but it happened also with previous versions too.

**Comment by JakeWharton** [comment]
This is most definitely a problem with your local Gradle install. Try removing the `.gradle` folder in your home directory so it's forced to redownload itself and then re-import into your IDE (or re-build from CLI). Works fine here in AS 1.2.2 and AS 1.3 with the included wrapper.

**Comment by tamminh** [comment]
Check your jdk version! The not-found class should be found in the version of the used jdk! The newest jdk does not always contain the missing class!
