### ISSUE TITLE
Disable Leak Canary and/or its activity

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/u2020#168]
Super annoying having it pollute your drawer. Either remove it altogether or figure out how to disable that damn launcher icon.

**Comment by mattprecious** [comment]
:+1:

**Comment by lennykano** [comment]
https://gist.github.com/lennykano/2bb061c9cff85b225590 is how I remove the launcher icon, but still leave the activity so I can access it through my own debug menu.

**Comment by lennykano** [comment]
Placed in the debug manifest of course
