### ISSUE TITLE
CreateProcess error=2

### ISSUE THREAD

**Issue by shizhongyu** [JakeWharton/u2020#234]
Error:(44, 0) CreateProcess error=2, The system cannot find the file specified
<a href="openFile:C:\Users\zhongyu\Desktop\u2020-master\u2020-master\build.gradle">Open File</a>

**Comment by JakeWharton** [comment]
There's not really enough information here to figure out what's happening or recommend any course of action. More info?

**Comment by droanmalik** [comment]
happens on `def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()` in build.gradle when importing project through android studio.

**Comment by droanmalik** [comment]
Fixed by adding git to PATH variable on windows.

**Comment by JakeWharton** [comment]
@mattprecious want to PR your internal fix for propagating exceptions here?
