### ISSUE TITLE
Debug drawer doesn't open in landscape

### ISSUE THREAD

**Issue by cxzhang2** [JakeWharton/u2020#247]
Nexus 5x on Marshmallow.

Soft navigation buttons block the right edge of the screen.  Can't open debug drawer.

![image](https://cloud.githubusercontent.com/assets/2879713/14118312/f3c62398-f5b6-11e5-8ee4-d7932fb145c8.png)

**Comment by mattprecious** [comment]
The drawer has a pretty large touch slop. You can press beside the navigation bar and it'll register as an edge press. It's not ideal, but it works.

**Comment by JakeWharton** [comment]
There's always going to be a configuration where the navigation bar ends up next to where the drawer should be opened. Internally we bind the spacebar to open the drawer for use on the emulator. Beyond that, like Matt said, putting your finger on the leftmost part of the app window will peek the drawer and allow it to be opened.
