### ISSUE TITLE
Broken talk link

### ISSUE THREAD

**Issue by Kisty** [JakeWharton/u2020#258]
Parleys.com is offline it seems. Looks like they've migrated to Youtube. Here's the youtube link:
https://www.youtube.com/watch?v=0XHx9jtxIxU

The broken link appears in the repo details and the README. I do a quick README.md correction but can't edit the description.

**Comment by Kisty** [comment]
Cheers. Can you also update the link in the repo description?

Currently it's: 
_A sample Android app which showcases advanced usage of Dagger among other open source libraries. http://parleys.com/play/529bde2ce4b0e619540cc3ae_

Change to:
_A sample Android app which showcases advanced usage of Dagger among other open source libraries. https://www.youtube.com/watch?v=0XHx9jtxIxU_

**Comment by JakeWharton** [comment]
Yep
