### ISSUE TITLE
Can't run project ?

### ISSUE THREAD

**Issue by chihung93** [JakeWharton/u2020#303]
I got a error when run project .

Could you please help me solve this problem ? Tks 

Error:(112, 0) Could not find method implementation() for arguments [com.android.support:support-v4:26.0.0-beta2] on object of type org.gradle.api.internal.artifacts.dsl.depend
<img width="765" alt="screen shot 2017-07-23 at 2 54 46 pm" src="https://user-images.githubusercontent.com/5199109/28497680-1b27b1f6-6fb7-11e7-8bfc-50ab3e009152.png">
encies.DefaultDependencyHandler.

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by JakeWharton** [comment]
Are you using AS 3.0?

**Comment by chihung93** [comment]
@JakeWharton : 
I'm using AS 2.3.3

**Comment by JakeWharton** [comment]
Using 3.0 canary is required for now.

**Comment by chihung93** [comment]
@JakeWharton 👍 
Now , I'm using AS 3.0 canary 

still got a error .

Error:Execution failed for task ':app:compileInternalDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

<img width="1266" alt="screen shot 2017-07-23 at 7 24 36 pm" src="https://user-images.githubusercontent.com/5199109/28499295-9c5058d0-6fdc-11e7-8dca-19ce154e023f.png">

**Comment by amardeshbd** [comment]
@chihung93 can you try clean build + rebuild project? also try from console using `./gradlew assembleDebug` both works fine for me. I am using AS 3.0 Canary 6.

**Comment by chihung93** [comment]
@amardeshbd : I do not know what steps I have missed?

```
./gradlew assembleDebug

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.pom
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.jar

> Task :app:compileInternalDebugJavaWithJavac
/Users/hungdct/Downloads/u2020-master/app/src/internalDebug/java/com/jakewharton/u2020/ui/debug/DebugView.java:19: error: cannot find symbol
import android.widget.TextView;
              ^
  symbol:   variable L
  location: class BuildConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/hungdct/Downloads/u2020-master/app/src/internalDebug/java/com/jakewharton/u2020/ui/debug/ContextualDebugActions.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileInternalDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
38 actionable tasks: 34 executed, 4 up-to-date

```

**Comment by amardeshbd** [comment]
I updated my AS to canary 7, just to make sure it's same as yours. It still works.
Looking at the error, I can't make sense out of it. What does `L` point to in the `BuildConfig` class?
