### ISSUE TITLE
Debug drawer widgets should be updated onResume to keep in sync with SharedPreferences

### ISSUE THREAD

**Issue by jacobtabak** [JakeWharton/u2020#35]
If you go to a second activity (ensuring that the previous activity is not destroyed), and change a setting in the debug drawer (such as latency), then go back to the first activity, the UI widgets in the debug drawer get out of sync with the preferences that back them since the widgets are only initialized in `onCreate()`.

I've worked around this in my application by removing the @Singleton annotations from the DebugAppContainer class and the module that provides it, and adding a second method `bind()` so the interface for AppContainer looks like this:

```java
ViewGroup get(Activity activity);
void bind(Activity activity);
```

Then I call `bind()` in onResume of my activity.

This adds a fair amount of complexity but is kind of necessary.  

Please let me know if you're interested in a PR.

**Comment by JakeWharton** [comment]
We're adding observable preferences. Started in #116 and see also https://github.com/JakeWharton/NotRxAndroid/issues/8.
