### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by AshkanImmortal** [JakeWharton/u2020#48]
Error:(45) A problem occurred evaluating root project 'u2020-master'.

> Cannot run program "git" (in directory "D:\Android\u2020-master"): CreateProcess error=2, The system cannot find the file specified

occurs at this line:
def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()

**Comment by micrologic** [comment]
Error(43.0)A problem occurred evaluating root project 'u2020-master'.
CreateProcess error=2,The system cannot find the file specified.
occurs at this line:
def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
But ,i have installed Git for Window 7

**Comment by adi1133** [comment]
Git needs to be in the windows PATH env variable.
Can you use git from the command line inside the project directory?
