### ISSUE TITLE
Add OkHttp cache info to drawer.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/u2020#61]

**Comment by raskasa** [comment]
I'm assuming you're looking to add the following to the drawer:
* `writeSuccessCount`
* `writeAbortCount`
* `networkCount`
* `hitCount`

Any others (i.e. `DiskLruCache#maxSize`)?

**Comment by JakeWharton** [comment]
Yes. There should also be a miss count.

**Comment by raskasa** [comment]
Looking for something like this?

![screen shot 2015-03-20 at 9 37 34 pm](https://cloud.githubusercontent.com/assets/1843059/6763214/7b6e196c-cf49-11e4-8a04-4a8325e86ed1.png)

I don't see a `#missCount()` method anywhere.  I'm assuming the user can imply how many misses by looking at the Hit Count.  But if a Miss Count field is preferred, I can add.

I'll submit the Pull Request after your feedback.

**Comment by JakeWharton** [comment]
Looks great!
